### ISSUE TITLE
Not Displaying

### ISSUE THREAD

**Issue by lunaristix** [MistyKnives/Kick-Discord-RPC#10] opened 2023-10-04 13:01 UTC
I can enter the initial information, but its not working for me. Once I get through the config panel, it doesnt push anything. Profile on discord stays [untouched[](url)](url)

**Comment by tyyzf** [comment] 2024-01-28 01:06
Hello,
Apologises for the very late answer. I am not maintaining this project at the moment so I have not been looking at the Github Repo.

This can be caused by many different issues, here are a few examples to look out for:

1. You're using an unsupported version of Discord which the RPC does not detect e.g. Vencord, etc. The dependency I use for the Discord side does not detect third party so it will not work.
2. You must make sure Rich Presence's are enabled in your Discord Settings by going to: 
Discord Settings -> Activity Privacy -> Display current activity as a status message. -> Enable.
3. The program itself is not detecting data from the Kick API and will not send to the Discord Client.

Here are many of the examples to look out for.

Like I said I am no longer supporting this project as there will eventually be a Kick RPC integrated into Discord anyways.

I hope you can get it to work if you haven't already. I will close this as completed but if you have any further issues you may reopen this or create a new issue.

Thank you.

**Closed as completed by tyyzf** 2024-01-28 01:06 UTC
